### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by stubbo** [Leurak/MEMZ#10]
i wish that i could fix this myself but no under standing of cpp so yeh :/

http://tinypic.com/r/ojqy42/9

**Comment by Leurak** [comment]
Did you change something? I never had compiling errors.

**Comment by Leurak** [comment]
Also, please upload screenshots here directly, as such sites, especially tinypic, suck.

**Comment by Leurak** [comment]
It seems like you compiled it with the wrong character encoding. Normally, that should be already set inside the build properties. But I'm changing most of the code anyways, so it should not happen anymore.

**Comment by Leurak** [comment]
Just found the issue inside your screenshot, you'll have to compile it for Release x86, not x64.
