### ISSUE TITLE
Reimplement the whole thing into Assembly

### ISSUE THREAD

**Issue by Leurak** [Leurak/MEMZ#18]
It might sound weird, but Assembly gives you way more control over everything.

If I'm creating my own build/link system, file sizes can be reduced and there will be less compatibility issues. Maybe it will even work on Windows 9X...

**Comment by Thesola10** [comment]
i was thinking about the `ld` tool from GNU Autotools

**Comment by Thesola10** [comment]
This issue is part of the process for #17 right?

**Comment by Leurak** [comment]
Maybe I'll do that. It would definetely be easier, but I also wanted to do a way to include your own payloads in form of some special executable format. But that won't get used anyway. And it would be a lot of useless work.

Why implement my own executable format, build and link system if there are things that already do that...

Will close this for now and create a new issue regarding a new build system.
