### ISSUE TITLE
//where can i get the...\\ Download link?

### ISSUE THREAD

**Issue by TheBigHacker0100** [Leurak/MEMZ#2]
Title says everything.

**Comment by cjhannah** [comment]
are you an idiot?

**Comment by TheBigHacker0100** [comment]
??? i want the virus for virtual testing

**Comment by cjhannah** [comment]
it's on danooct1's forum

**Comment by cjhannah** [comment]
you can also get it at http://idontknowwhatimdoing.space/stuff/MEMZ-Destructive.exe

**Comment by Leurak** [comment]
Don't share malware in here @cjhannah
