### ISSUE TITLE
That MBR is beautiful

### ISSUE THREAD

**Issue by fennectech** [Leurak/MEMZ#4]
i have an idea    Is it possable to chainload this from grub?

**Comment by Thesola10** [comment]
Maybe making the MBR into a multiboot kernel

**Comment by Leurak** [comment]
It should be possible with floppy emulation. It's definetely possible to create a bootable ISO. The bootloader just needs to load the boot image at the right address in memory and jump to it. This should *normally* be possible in all bootloaders, however, I did not try it.

**Comment by Leurak** [comment]
I guess this has been resolved?
