### ISSUE TITLE
Make For Linux

### ISSUE THREAD

**Issue by Articuno1234** [Leurak/MEMZ#48]
Please make MEMZ usable on linux devices please :D

**Comment by Thesola10** [comment]
Sure, but that would take a major rework of the injector program. i might start looking into native X.org libs to reproduce MEMZ's effects but until then, slim chance.
Also the payload injection will require root permissions, which would be suspicious...

**Comment by Leurak** [comment]
MEMZ is built almost only using Windows syscalls. Porting would mean completely rewriting it, which is way too much work.

**Comment by sourceprocoder** [comment]
### As I think:
You'll need to compile it in `Windows NT` and run in Linux using WINE!

**Comment by jlagarespo** [comment]
Some people already did run it using WINE, and it gives pretty good results, but as Leurak said, porting the entire MEMZ natively to Linux would mean rewriting all syscalls it does, and WINE already does that work for you. Also, @sourceprocoder of course you need to compile it in Windows NT, as it has always been, I mean would you seriously compile it in Windows 9x?
