### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by MiroslavRD** [Leurak/MEMZ#64]
We invite you to the Melancholy project.
Can you please work there?
https://github.com/MiroslavRD/Melancholy/invitations

**Comment by jlagarespo** [comment]
And what is Melancholy project suposed to be?
Im not Leurak, but im sure you should provide more information.

**Comment by MiroslavRD** [comment]
It's a evil windows wabbit bios/loader virus

**Comment by MiroslavRD** [comment]
Sorry but melancholy is closed due to data breach.

**Comment by jlagarespo** [comment]
?????
Data breach? Advanced HTML code? BIOS flashing? Ok, I am officially confused.
What does data breach mean? Did something important get compromissed?
How do you even BIOS flash in this days?(i mean, Leurak has a prototype but it shouldn't work in modern EFI computers.
And what do you mean by "HTML"? What does HTML have to do with all this?

**Comment by MiroslavRD** [comment]
HAHAHAHAHAHA YOU JUST GOT APRIL FOOLED!

**Comment by jlagarespo** [comment]
Wait a minnute. I just realized the date

**Comment by MiroslavRD** [comment]
LOL

**Comment by MiroslavRD** [comment]
I deleted the repository of Melancholy virus

**Comment by MiroslavRD** [comment]
Because it's a april fools joke

**Comment by MiroslavRD** [comment]
And april fools is ending soon in my timezone

**Comment by jlagarespo** [comment]
But was it even real? Also, please don't write so spammy, write all messages in a single comment.

**Comment by MiroslavRD** [comment]
I'm sorry but Melancholy was a joke

**Comment by jlagarespo** [comment]
Oh ok, that's fine. I didn't even realize the date until now tbh
