### ISSUE TITLE
Individual Payloads

### ISSUE THREAD

**Issue by FlappyDude2003** [Leurak/MEMZ#65]
Can someone make all the payloads into individual executables or at least show me how to do it myself? Whenever i try to compile the .c's from the payloads i always get errors.

**Comment by jlagarespo** [comment]
Have you at least read the files that you are trying to compile? They are not individual, they need each other to work. Also you should need to give more information: what are the errors? What platform are you building MEMZ on? Are you trying to build the entire thing(just run ``make`` on both the mbr and the exe itself) or just create your own version?

**Comment by FlappyDude2003** [comment]
Noo im trying to be able to use the payloads individually. Like whats the code for each payloads and what language are they using?

**Comment by Dobby233Liu** [comment]
> Noo im trying to be able to use the payloads individually. Like whats the code for each payloads and what language are they using?

C

**Comment by FlappyDude2003** [comment]
do you know how to make the scripts work by themselves by compiling them? can you help me?

**Comment by Dobby233Liu** [comment]
> do you know how to make the scripts work by themselves by compiling them? can you help me?

rewrite the memz payload engine, maybe

**Comment by FlappyDude2003** [comment]
but wouldn’t that make all the scripts activate at once? i just want individual executables for each script or at least the code for them so i can compile them myself.

**Comment by jlagarespo** [comment]
Im sorry, i think im missing something: what scripts? What scripts are you talking about? Are you talking about the batch generated output?

**Comment by FlappyDude2003** [comment]
sorry not scripts, payloads. an example of what i mean is do you know the tunnel effect payload? how would i get just the code for that payload to make it an executable so that when i run it, it does the tunnel effect?

**Comment by jlagarespo** [comment]
A first good step would be to learn programming...

**Comment by FlappyDude2003** [comment]
ok but is that possible?

**Comment by Dobby233Liu** [comment]
https://github.com/Dobby233Liu/MEMZPayloads
working on it

**Comment by jlagarespo** [comment]
@FlappyDude2003 of course it is possible, aren't we in a turing machine?
But if what you expect is for someone to give you a working thing and then claim it for yourself, then it is not the way to do it. Learn programming and try to understand the code, or else nothing here makes any sense at all. A good way to start would be to read this https://www.dipmat.univpm.it/~demeio/public/the_c_programming_language_2.pdf (i have the physical version from the time it was published), but it is a bit old, so also this https://www.learn-c.org/.

**Comment by FlappyDude2003** [comment]
thanks for the help man, i was just looking for how to get the code for the program so i can understand it and compile it myself.

**Comment by Dobby233Liu** [comment]
@FlappyDude2003 So can this issue been closed now?
